<?php
/**
 * @file
 * openbiz_news_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function openbiz_news_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'lacinia ac venenatis at',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '700947c7-98e8-4be8-9177-3bf7c349f914',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458255482,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3406f086-3009-4fff-8fc1-b4fff4842912',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 09:58:02 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Proin facilisis convallis ante',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '37551b2e-9a7c-4155-8616-a5000811e025',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256115,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '648a7f11-3a8e-4bee-b459-7fa98a46d9fa',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:08:35 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Quisque elementum molestie ante eget rhoncus',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '895e51e3-9c88-4fd3-bd9a-65e84e23f842',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256006,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6558ab5e-0649-40c4-8f85-d59ccc4d9338',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:06:46 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'In vitae molestie sapien, eget varius turpis',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '1f5d1a0a-e000-4b6e-bf91-c1866ad908b7',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256792,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '85baeaa3-16f0-44c6-9fe4-5c409364a83a',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:19:52 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Quisque iaculis tellus vitae neque',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '788584e3-e960-48b2-a298-89d5eb018d0f',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256141,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8f851fd7-1fcd-4778-b139-692d4caaa90f',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:09:01 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Nunc nec nibh cursus, tincidunt sem eget',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'e550f489-75a6-4299-a016-a4b389f506e6',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458255972,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '912f06de-f747-47ea-ae21-695b14a1b1b1',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:06:12 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Integer interdum neque in dignissim dignissim',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '94be89ce-c3f5-4cc6-92b9-2986be6b8d9a',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256882,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'afb54bd5-5624-43ed-92b7-0edd1e6470f3',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:21:22 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => ' Aliquam massa metus, pulvinar vel lacus eu',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '333cfa09-d144-416c-ace5-99f4ab76dcb8',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256034,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd7043db1-2458-45f7-b1c2-5533e6575a35',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:07:14 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Suspendisse convallis, erat ac pulvinar molestie',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'aa61d866-16fa-494e-a1ea-1ddde5463bd8',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256054,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f3771b41-0399-47a2-ab0a-13e72a0b0cd4',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:07:34 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Cras molestie elementum massa convallis varius',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '2c803284-01f1-4f13-8634-e46d444d1ed0',
  'type' => 'news',
  'language' => 'und',
  'created' => 1458256823,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f7e6dde8-f978-447d-956b-bfc8fda34581',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>

<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>

<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>

<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>

<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam massa metus, pulvinar vel lacus eu, efficitur tempor metus. Suspendisse convallis, erat ac pulvinar molestie, mi risus faucibus mi, eget lobortis lectus sapien vel sapien. Quisque eleifend dui id urna maximus, sit amet ultrices tellus elementum. Aenean ut placerat nisl. Proin facilisis convallis ante, aliquet porttitor mi aliquam in. Nulla quis dapibus risus. Sed quis ultrices enim, quis dictum risus. Etiam ultrices dapibus lorem quis sodales. Ut placerat leo porta, vehicula tortor eget, tristique mi. Aenean pulvinar nulla ut sapien luctus ultricies. Quisque elementum molestie ante eget rhoncus. Quisque iaculis tellus vitae neque imperdiet, ultrices mollis tortor aliquam. Aliquam blandit purus vitae aliquet pulvinar. Sed facilisis, libero et lobortis dapibus, tellus turpis dapibus libero, eu dictum nunc tortor quis justo. Aenean scelerisque sem nec sapien molestie maximus.</p>
<p>Etiam in semper nisi, ut posuere nisl. Nam id varius lacus, ac aliquam sem. Mauris consequat massa dictum, tristique nisi a, venenatis velit. Suspendisse potenti. Nullam ac leo magna. In vitae molestie sapien, eget varius turpis. Mauris eu volutpat ante, vel viverra turpis. Maecenas vel nisi tempus, venenatis dui eu, aliquam sem. Quisque non elementum massa. Sed et odio eu nisl iaculis dictum. Pellentesque et orci vel dui pharetra suscipit ut ut urna. Aliquam varius bibendum maximus. Nam lacinia quam ut leo facilisis, ut imperdiet elit accumsan. Quisque vitae est suscipit, porttitor lacus in, vehicula neque.</p>
<p>Curabitur dignissim eleifend quam, ac blandit metus tempus ac. Cras molestie elementum massa convallis varius. Vestibulum magna nibh, fringilla eget efficitur accumsan, semper et massa. In hac habitasse platea dictumst. Sed at odio vulputate, posuere arcu et, vestibulum dolor. Nunc nec nibh cursus, tincidunt sem eget, molestie neque. Maecenas viverra interdum viverra.</p>
<p>Praesent in ipsum non tortor congue pulvinar congue vel lorem. Vivamus egestas magna vitae feugiat varius. Vestibulum vestibulum commodo augue ac rutrum. Morbi placerat ex sed cursus varius. Phasellus ut egestas lorem. Vivamus ultrices eros at pulvinar dictum. Proin sagittis, nulla quis ornare ornare, ligula ipsum rhoncus lectus, vel molestie lectus magna sed quam. Duis pellentesque ex ex, quis interdum leo ornare in.</p>
<p>Ut ipsum sem, pellentesque non tellus et, hendrerit ultrices urna. Vivamus dictum, turpis vel tempus venenatis, tortor ipsum tincidunt tellus, sit amet malesuada sapien enim nec purus. Morbi rhoncus ultricies commodo. Integer interdum neque in dignissim dignissim. In ut enim lectus. Proin fringilla nisi sit amet sollicitudin sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ut urna vitae eros ullamcorper rhoncus a condimentum purus. Maecenas non finibus lectus, ac pretium eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit ex, lacinia ac venenatis at, vestibulum a diam. Donec sit amet justo arcu.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-18 10:20:23 +1100',
);
  return $nodes;
}
