language: php
sudo: required

php:
  - 5.6
  - 7.0
  - hhvm

# Build matrix options
matrix:
  allow_failures:
    - php: 7
    - php: hhvm
  fast_finish: true

mysql:
  database: openbiz
  username: root
  encoding: utf8

branches:
  except:
    - master

cache:
  bundler: true
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - "mysql -e 'create database openbiz;'"

  - travis_retry composer install --working-dir=build --prefer-source
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/build/bin

before_script:
  # Disable xdebug for speed.
  # NB: this should NOT be done for hhvm and php 7.0.
  # Also we use the php 5.6 run to generate code coverage reports, and we need xdebug for that
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7.0" -a "$TRAVIS_PHP_VERSION" != "5.6" ]; then phpenv config-rm xdebug.ini; fi

  # Sendmail support.
  - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e 'sendmail_path = /bin/true' | sudo tee -a /etc/hhvm/php.ini; fi

script:
  - ./build/build.sh

after_script:
  - cd $TRAVIS_BUILD_DIR/docroot
  - drush status