language: php
sudo: required

php:
  - 5.6
  - 7.0
  - hhvm

# Build matrix options
matrix:
  allow_failures:
    - php: 7
    - php: hhvm
  fast_finish: true

mysql:
  database: openbiz
  username: root
  encoding: utf8

branches:
  except:
    - master

cache:
  bundler: true
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - "mysql -e 'create database openbiz;'"

  - travis_retry composer install --working-dir=build --prefer-source
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/build/bin

before_script:
  # Sendmail support.
  - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  # hhvm ignores sendmail_path and hhvm.mail.sendmail_path settings presently...
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then sudo ln -s /bin/true /usr/local/bin/sendmail; fi

  # Prepare logs
  - mkdir -p build/logs

script:
  - ./build/build.sh