<?php
/**
 * @file
 * openbiz_blog_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function openbiz_blog_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Donec eget malesuada libero',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'd683c8b9-3552-4384-aef6-a1135b2bb154',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1458206422,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '961f5ecd-cd7e-4071-afae-fbce57c79ee3',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed enim diam, convallis sed justo nec, feugiat accumsan ligula. Nullam non scelerisque elit, a pulvinar purus. Morbi non augue imperdiet tellus mattis rhoncus ac at leo. Pellentesque dictum eros eget velit ultrices tempus. Fusce sit amet blandit enim. In consequat, lacus vitae auctor ultricies, felis lectus condimentum eros, sit amet mollis enim augue vitae metus. Curabitur rutrum efficitur tempor. Vestibulum a bibendum sem. Ut libero magna, consequat eu facilisis eget, tristique in eros. Etiam commodo sagittis augue nec sodales.</p>

<p>Aenean vel massa elit. Donec ullamcorper, nisl non molestie vulputate, felis augue pretium est, vitae interdum ligula tortor nec libero. Vivamus ut justo ultrices, tristique lectus id, hendrerit sapien. Donec vestibulum consequat ipsum nec imperdiet. Donec vehicula eleifend dolor ac dictum. Mauris eleifend erat eget eleifend tincidunt. Suspendisse auctor, elit id maximus dignissim, dui ipsum varius elit, sit amet pellentesque dui magna quis turpis.</p>

<p>Donec eget malesuada libero. Donec mattis risus nunc, in aliquam mi efficitur a. Quisque fringilla elit et ipsum varius, sit amet rutrum turpis finibus. Integer cursus iaculis dolor at sodales. Nunc sit amet diam pellentesque, maximus ex eget, eleifend nulla. Cras non lacus eu risus ornare mollis. Nullam blandit erat nisi, vehicula lacinia magna laoreet id. Ut suscipit ultricies felis in imperdiet. Mauris sit amet condimentum libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce auctor magna dui.</p>

<p>Pellentesque accumsan eu metus sed tempor. Fusce quam elit, volutpat eu ante sed, vulputate lacinia odio. Morbi eleifend, neque vulputate feugiat pulvinar, leo risus placerat felis, ut dignissim mauris tellus at ligula. Nullam vulputate dapibus ultricies. Cras libero augue, egestas quis felis rhoncus, dictum porta ligula. Integer aliquet felis rutrum odio tristique rhoncus. Nullam mattis interdum sem a feugiat. Mauris sed nisl sed velit volutpat venenatis. Nullam eget vestibulum ligula, quis posuere felis. Etiam ut sapien consequat, placerat elit sed, congue mauris. Etiam eget sagittis augue, et commodo ante. Aliquam erat volutpat. Duis ipsum nunc, egestas vel lorem quis, malesuada sodales mauris. Aenean ornare commodo nulla nec egestas. Donec in aliquet sapien.</p>

<p>Curabitur ac eleifend nunc. Nulla gravida sagittis lectus vel elementum. Fusce volutpat iaculis nunc quis aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur dolor malesuada facilisis pharetra. Morbi sagittis finibus augue vitae fermentum. In vulputate dapibus mauris, quis accumsan sapien vestibulum et. Pellentesque malesuada nibh eu augue mollis, vel maximus elit suscipit. Curabitur ut velit pretium, placerat orci eu, cursus purus. Sed placerat dolor id odio fermentum porttitor. Etiam convallis lacus eros, eget cursus mi tincidunt sit amet. Fusce pulvinar odio lacus, ut commodo leo pellentesque at.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed enim diam, convallis sed justo nec, feugiat accumsan ligula. Nullam non scelerisque elit, a pulvinar purus. Morbi non augue imperdiet tellus mattis rhoncus ac at leo. Pellentesque dictum eros eget velit ultrices tempus. Fusce sit amet blandit enim. In consequat, lacus vitae auctor ultricies, felis lectus condimentum eros, sit amet mollis enim augue vitae metus. Curabitur rutrum efficitur tempor. Vestibulum a bibendum sem. Ut libero magna, consequat eu facilisis eget, tristique in eros. Etiam commodo sagittis augue nec sodales.</p>
<p>Aenean vel massa elit. Donec ullamcorper, nisl non molestie vulputate, felis augue pretium est, vitae interdum ligula tortor nec libero. Vivamus ut justo ultrices, tristique lectus id, hendrerit sapien. Donec vestibulum consequat ipsum nec imperdiet. Donec vehicula eleifend dolor ac dictum. Mauris eleifend erat eget eleifend tincidunt. Suspendisse auctor, elit id maximus dignissim, dui ipsum varius elit, sit amet pellentesque dui magna quis turpis.</p>
<p>Donec eget malesuada libero. Donec mattis risus nunc, in aliquam mi efficitur a. Quisque fringilla elit et ipsum varius, sit amet rutrum turpis finibus. Integer cursus iaculis dolor at sodales. Nunc sit amet diam pellentesque, maximus ex eget, eleifend nulla. Cras non lacus eu risus ornare mollis. Nullam blandit erat nisi, vehicula lacinia magna laoreet id. Ut suscipit ultricies felis in imperdiet. Mauris sit amet condimentum libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce auctor magna dui.</p>
<p>Pellentesque accumsan eu metus sed tempor. Fusce quam elit, volutpat eu ante sed, vulputate lacinia odio. Morbi eleifend, neque vulputate feugiat pulvinar, leo risus placerat felis, ut dignissim mauris tellus at ligula. Nullam vulputate dapibus ultricies. Cras libero augue, egestas quis felis rhoncus, dictum porta ligula. Integer aliquet felis rutrum odio tristique rhoncus. Nullam mattis interdum sem a feugiat. Mauris sed nisl sed velit volutpat venenatis. Nullam eget vestibulum ligula, quis posuere felis. Etiam ut sapien consequat, placerat elit sed, congue mauris. Etiam eget sagittis augue, et commodo ante. Aliquam erat volutpat. Duis ipsum nunc, egestas vel lorem quis, malesuada sodales mauris. Aenean ornare commodo nulla nec egestas. Donec in aliquet sapien.</p>
<p>Curabitur ac eleifend nunc. Nulla gravida sagittis lectus vel elementum. Fusce volutpat iaculis nunc quis aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur dolor malesuada facilisis pharetra. Morbi sagittis finibus augue vitae fermentum. In vulputate dapibus mauris, quis accumsan sapien vestibulum et. Pellentesque malesuada nibh eu augue mollis, vel maximus elit suscipit. Curabitur ut velit pretium, placerat orci eu, cursus purus. Sed placerat dolor id odio fermentum porttitor. Etiam convallis lacus eros, eget cursus mi tincidunt sit amet. Fusce pulvinar odio lacus, ut commodo leo pellentesque at.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_category' => array(),
  'field_blog_tags' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-17 20:20:22 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Lorem ipsum dolor sit amet',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '0ad2a149-9923-49c3-a579-fb100ff0d00d',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1458206384,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'db8ef6b7-6cde-4b86-98ca-0072cfe371a7',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo odio quis sem posuere, at interdum mauris laoreet. Fusce eleifend eros sit amet porta efficitur. In pellentesque purus non urna tincidunt cursus. Phasellus auctor eros et eleifend ullamcorper. Nullam mauris magna, vestibulum sed leo nec, lacinia tempus ex. Nulla porttitor turpis ac efficitur ultricies. Vestibulum ultrices imperdiet mi. Sed sed tincidunt lacus. Maecenas non interdum sem. Cras et lobortis augue, in facilisis enim. Etiam tempus mi tortor, et mollis massa commodo sed. Praesent ut egestas sapien, eu ullamcorper augue. Quisque eget orci magna. Ut vulputate, elit et efficitur rhoncus, dolor ex volutpat ante, eget dignissim justo erat et lacus. Maecenas sem erat, feugiat nec efficitur rhoncus, convallis in odio. Sed vehicula augue id cursus lobortis.</p>

<p>Suspendisse elementum varius tortor aliquet suscipit. Fusce tempor velit ut odio cursus venenatis. Morbi eu viverra nisl. Nulla euismod elit a suscipit feugiat. Integer ac volutpat sapien, accumsan finibus arcu. Nulla et lacus fringilla, consectetur lectus in, dapibus lectus. Sed aliquet ligula leo, vehicula accumsan justo iaculis sit amet. Quisque a ullamcorper lectus. Aliquam mollis ipsum id ligula elementum suscipit.</p>

<p>Mauris imperdiet porta ante non tempor. Ut varius eros vel augue tempor facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sed tristique nisl. Maecenas posuere, velit et sollicitudin interdum, tellus lacus vestibulum mi, convallis vulputate orci enim in libero. Phasellus laoreet ultrices lacus, in venenatis elit lobortis eget. Sed efficitur laoreet nulla eu semper. Curabitur id laoreet orci. Aenean vitae erat et ante aliquam vulputate.</p>

<p>Morbi odio enim, finibus iaculis convallis sed, fringilla eget libero. Fusce suscipit erat tempor neque sagittis, nec faucibus magna lacinia. Suspendisse massa nisl, dictum id eros sed, lobortis hendrerit dolor. Cras elit dolor, pulvinar scelerisque quam convallis, scelerisque blandit est. Praesent quis est sollicitudin, scelerisque mauris quis, rutrum tellus. Nunc faucibus bibendum nibh consequat mattis. Integer ullamcorper, turpis ac gravida euismod, nulla leo rhoncus velit, eget tincidunt est ex et sapien. Donec nunc est, dictum vel auctor id, tempor ac orci. In rhoncus leo ac justo suscipit vulputate.</p>

<p>Proin non lectus in augue sollicitudin vulputate. Donec ornare sagittis tortor, at cursus lorem. Nam eleifend lorem sit amet leo auctor, vel semper augue iaculis. Duis tempor bibendum ligula non varius. Morbi ultricies at nibh a pulvinar. Vestibulum lacinia nibh sed felis feugiat, pretium dignissim nisl elementum. Proin at felis eu tellus luctus pellentesque ac sed turpis.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo odio quis sem posuere, at interdum mauris laoreet. Fusce eleifend eros sit amet porta efficitur. In pellentesque purus non urna tincidunt cursus. Phasellus auctor eros et eleifend ullamcorper. Nullam mauris magna, vestibulum sed leo nec, lacinia tempus ex. Nulla porttitor turpis ac efficitur ultricies. Vestibulum ultrices imperdiet mi. Sed sed tincidunt lacus. Maecenas non interdum sem. Cras et lobortis augue, in facilisis enim. Etiam tempus mi tortor, et mollis massa commodo sed. Praesent ut egestas sapien, eu ullamcorper augue. Quisque eget orci magna. Ut vulputate, elit et efficitur rhoncus, dolor ex volutpat ante, eget dignissim justo erat et lacus. Maecenas sem erat, feugiat nec efficitur rhoncus, convallis in odio. Sed vehicula augue id cursus lobortis.</p>
<p>Suspendisse elementum varius tortor aliquet suscipit. Fusce tempor velit ut odio cursus venenatis. Morbi eu viverra nisl. Nulla euismod elit a suscipit feugiat. Integer ac volutpat sapien, accumsan finibus arcu. Nulla et lacus fringilla, consectetur lectus in, dapibus lectus. Sed aliquet ligula leo, vehicula accumsan justo iaculis sit amet. Quisque a ullamcorper lectus. Aliquam mollis ipsum id ligula elementum suscipit.</p>
<p>Mauris imperdiet porta ante non tempor. Ut varius eros vel augue tempor facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sed tristique nisl. Maecenas posuere, velit et sollicitudin interdum, tellus lacus vestibulum mi, convallis vulputate orci enim in libero. Phasellus laoreet ultrices lacus, in venenatis elit lobortis eget. Sed efficitur laoreet nulla eu semper. Curabitur id laoreet orci. Aenean vitae erat et ante aliquam vulputate.</p>
<p>Morbi odio enim, finibus iaculis convallis sed, fringilla eget libero. Fusce suscipit erat tempor neque sagittis, nec faucibus magna lacinia. Suspendisse massa nisl, dictum id eros sed, lobortis hendrerit dolor. Cras elit dolor, pulvinar scelerisque quam convallis, scelerisque blandit est. Praesent quis est sollicitudin, scelerisque mauris quis, rutrum tellus. Nunc faucibus bibendum nibh consequat mattis. Integer ullamcorper, turpis ac gravida euismod, nulla leo rhoncus velit, eget tincidunt est ex et sapien. Donec nunc est, dictum vel auctor id, tempor ac orci. In rhoncus leo ac justo suscipit vulputate.</p>
<p>Proin non lectus in augue sollicitudin vulputate. Donec ornare sagittis tortor, at cursus lorem. Nam eleifend lorem sit amet leo auctor, vel semper augue iaculis. Duis tempor bibendum ligula non varius. Morbi ultricies at nibh a pulvinar. Vestibulum lacinia nibh sed felis feugiat, pretium dignissim nisl elementum. Proin at felis eu tellus luctus pellentesque ac sed turpis.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_category' => array(),
  'field_blog_tags' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-17 20:19:44 +1100',
);
  return $nodes;
}
