<?php
/**
 * @file
 * openbiz_media_release_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function openbiz_media_release_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Ut libero diam, dignissim in facilisis a, feugiat id tellus',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'da8069b2-d27f-4a9f-9fc8-56fcf5112964',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360920,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '264af6cf-a4fc-4e57-b5c8-c9299764e0a0',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:15:20 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Nunc cursus enim id nisl tempus',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3c4f65c4-ef70-44ba-b440-88f7ad0cfaee',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360833,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '306da31a-6a33-495e-9fe0-7354c62ff2c1',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:13:53 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Quisque mauris libero, consectetur consequat nisi ac',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4aa528a3-5d77-4b21-8a01-d0ea9d6e678f',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360940,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3fc121fa-a852-4142-9832-17c0b6135a66',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:15:40 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Aenean imperdiet magna lorem, at varius ligula efficitur',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '18c1b584-85cf-4221-bed3-eea381e78446',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458361057,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4df46899-39d7-41f1-9184-c9ac86a190d0',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:17:37 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Cras pulvinar nunc sed purus vestibulum aliquet',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5851e172-19ce-4c45-afbe-af9211b244b5',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458361001,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '73179e21-7d14-4754-ac04-7dd967208ea6',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:16:41 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Nam sodales, risus sit amet tincidunt finibus',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '43b3325c-d9c6-4443-b6fa-72895889c504',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360899,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8edaa46b-6c63-4203-977d-7152facf2a6d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:14:59 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Vestibulum et malesuada elit',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3cbb1780-8ef6-4ccc-b4a3-9796996768b4',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360881,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'aeadaa5e-10c3-4dea-9869-c0c3e0f60574',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:14:41 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Proin elit justo, condimentum et magna id',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7933413f-0e90-451a-875e-ce08fc872692',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360861,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e465fff0-eacd-47ea-baed-b3a4b39e991a',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:14:21 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Nam in elit nulla. Suspendisse diam tellus',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4dd3d1bd-f453-452a-b6f2-f31d6f7b9730',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458361028,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f37906c8-dd61-4631-a3bd-740569a42ce8',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:17:08 +1100',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Praesent venenatis, ex quis congue aliquam',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'db7ec564-e4e7-4f21-b642-9eb62d7d165e',
  'type' => 'media_release',
  'language' => 'und',
  'created' => 1458360961,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f54e1dc7-5e43-4254-89c1-e9496d167826',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>

<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>

<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>

<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>

<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis odio eu varius ornare. Vestibulum et malesuada elit, eu vestibulum leo. Quisque tristique congue arcu. Nam sodales, risus sit amet tincidunt finibus, velit nibh tincidunt odio, non aliquet tellus dui quis mi. Vivamus pulvinar turpis sit amet arcu sagittis fringilla. Vestibulum sed nisl tempor, pharetra ipsum non, tempus lorem. Etiam augue ante, posuere id facilisis ac, accumsan quis mi. Ut libero diam, dignissim in facilisis a, feugiat id tellus. Quisque mauris libero, consectetur consequat nisi ac, iaculis pulvinar felis. Ut euismod tincidunt libero, nec gravida mauris aliquam sed. Etiam elementum efficitur ipsum in efficitur. Praesent venenatis, ex quis congue aliquam, augue lacus efficitur nibh, at euismod velit elit non lorem. In hac habitasse platea dictumst.</p>
<p>Duis scelerisque odio consequat, venenatis diam vitae, consequat enim. Fusce interdum vehicula mollis. Ut egestas, libero a tincidunt faucibus, mauris lacus rutrum lectus, sit amet ultrices eros erat quis mauris. Suspendisse feugiat elementum luctus. Proin bibendum nisi tortor, sed venenatis mi viverra non. Quisque ac nisi quam. Nunc cursus enim id nisl tempus, ut tincidunt urna ornare. Proin elit justo, condimentum et magna id, pellentesque sodales nunc.</p>
<p>Maecenas fringilla, lectus a interdum venenatis, nisi nisi accumsan neque, vel sodales tellus quam egestas lacus. Vestibulum iaculis mauris ut dui pellentesque aliquam. Nulla bibendum ex sit amet rutrum porta. Fusce at sem lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent a mauris sit amet tellus bibendum iaculis. Nullam vestibulum, quam id elementum tempor, urna erat hendrerit risus, ut hendrerit ipsum tortor vel tellus. Mauris efficitur scelerisque vehicula. Praesent id diam et augue pellentesque lobortis. Aliquam sagittis, neque non dignissim blandit, ipsum nunc sollicitudin nunc, id ultricies urna arcu at elit. Duis eu lorem nec diam finibus tempor. Integer faucibus finibus massa, ut rhoncus metus posuere id.</p>
<p>Nulla tempor gravida ipsum, at facilisis est malesuada vel. Vestibulum faucibus facilisis placerat. Ut arcu sapien, aliquam laoreet ullamcorper in, vehicula quis massa. Quisque at mi vitae est fermentum tristique nec consectetur quam. Nulla commodo condimentum urna vel sodales. Nam malesuada, elit ornare venenatis viverra, dolor tortor eleifend sapien, vel maximus lectus odio vel ante. Nulla in nisl sit amet nisi varius lobortis. Aliquam a nunc quis sapien tincidunt scelerisque. Pellentesque ut ex lacinia, tempus quam et, fringilla velit. Praesent vel purus id risus convallis pretium. Cras pulvinar nunc sed purus vestibulum aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean quis mollis odio. Aenean imperdiet magna lorem, at varius ligula efficitur sed. In est elit, efficitur vitae dui at, tempus eleifend lorem.</p>
<p>Duis in aliquet massa, et iaculis ex. Mauris tempor volutpat turpis, gravida eleifend lectus feugiat nec. Donec at erat eget nisl laoreet porta et eget tortor. Nam sit amet tellus ac nulla euismod viverra sed sed velit. Nunc pellentesque placerat pretium. Nulla pretium consectetur commodo. Praesent nunc nulla, volutpat eu luctus ac, varius ut felis. Nam in elit nulla. Suspendisse diam tellus, ultrices eu tincidunt in, finibus in quam. Suspendisse non aliquet enim. Praesent iaculis eleifend enim, et porttitor felis pretium in. Cras sollicitudin tellus dictum, auctor nisi et, aliquam tortor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:1:{s:7:"contact";i:1;}',
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-19 15:16:01 +1100',
);
  return $nodes;
}
