<?php
/**
 * @file
 * openbiz_standard_page_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function openbiz_standard_page_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'About Us',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5edfbab5-c4cb-4c5b-b278-1095b1e61cfa',
  'type' => 'page',
  'language' => 'und',
  'created' => 1458204552,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a23167f1-c410-42c7-8e10-def23a62dc6c',
  'revision_uid' => 0,
  'body' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-17 19:49:12 +1100',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'fe2aada6-2827-43cc-9f2c-7bf457e1c588',
  'type' => 'page',
  'language' => 'und',
  'created' => 1458204692,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a91ea950-c9de-4328-a02a-25afd6b46334',
  'revision_uid' => 0,
  'body' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-17 19:51:32 +1100',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Privacy',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '778a4f86-dc28-4bc4-b6fa-1c639358dc4e',
  'type' => 'page',
  'language' => 'und',
  'created' => 1458204635,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bedd7408-f7bf-4f27-84c2-c6ec38c98806',
  'revision_uid' => 0,
  'body' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'pathauto_perform_alias' => FALSE,
  'date' => '2016-03-17 19:50:35 +1100',
);
  return $nodes;
}
